CREATE TABLE COMPANY (
	CID NUMBER(3) PRIMARY KEY,
	CNAME VARCHAR2(30) NOT NULL,
	CLOCATION VARCHAR2(30) NOT NULL
);

CREATE TABLE EMPLOYER (
	YERID NUMBER(3) PRIMARY KEY,
	YERNAME VARCHAR2(30) NOT NULL,
	USERNAME VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(30) NOT NULL,
	CID NUMBER(3) NOT NULL,

	constraint YER_COMP foreign key (CID) references COMPANY(CID)
	);

CREATE TABLE EMPLOYEE (
	YEEID NUMBER(3) PRIMARY KEY,
	YEENAME VARCHAR2(30) NOT NULL,
	YEESURNAME VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	JOB VARCHAR2(30) NOT NULL,
	WAGE NUMBER(4,2) NOT NULL,
	PARTIME BOOLEAN DEFAULT FALSE,
	CID NUMBER(3),

	constraint YEE_COMP foreign key (CID) references COMPANY(CID),
	constraint EMAIL_CHK check (EMAIL LIKE '%___@___%');
	);


CREATE TABLE TIMETABLE (
	TID NUMBER(3) PRIMARY KEY,
	DAYOFWEEK NUMBER(1),
	STARTTIME TIMESTAMP NOT NULL,
	ENDTIME TIMESTAMP NOT NULL,
	TASKDESC VARCHAR2(50),
	CHECKEDIN BOOLEAN DEFAULT FALSE,
	PAYMENT NUMBER(4,2),
	YEEID NUMBER(3),

	constraint TIME_YEE foreign key (YEEID) references EMPLOYEE(YEEID)

	);