CREATE TABLE COMPANY (
	CID INT(3) PRIMARY KEY AUTO_INCREMENT,
	CNAME VARCHAR(30) NOT NULL,
	CLOCATION VARCHAR(30) NOT NULL
);

CREATE TABLE EMPLOYER (
	YERID INT(3) PRIMARY KEY AUTO_INCREMENT,
	YERNAME VARCHAR(30) NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	CID INT(3),

	constraint YER_COMP foreign key (CID) references COMPANY(CID)
	);

CREATE TABLE EMPLOYEE (
	YEEID INT(3) PRIMARY KEY AUTO_INCREMENT,
	YEENAME VARCHAR(30) NOT NULL,
	YEESURNAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	JOB VARCHAR(30) NOT NULL,
	WAGE DECIMAL(4,2) NOT NULL,
	PARTIME BOOLEAN DEFAULT FALSE,
	CID INT(3),

	constraint YEE_COMP foreign key (CID) references COMPANY(CID)
	);


CREATE TABLE TIMETABLE (
	TID INT(3) PRIMARY KEY AUTO_INCREMENT,
	DAYOFWEEK INT(1),
	STARTTIME TIMESTAMP NOT NULL,
	ENDTIME TIMESTAMP NOT NULL,
	TASKDESC VARCHAR(50),
	CHECKEDIN BOOLEAN DEFAULT FALSE,
	PAYMENT DECIMAL(4,2),
	YEEID INT(3),

	constraint TIME_YEE foreign key (YEEID) references EMPLOYEE(YEEID)

	);